name: hello worls
on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello world!"
#dkdlkfdfndn