name: input test
on:
  workflow dispatch:
    inputs:
      environment:
        description: this is the name input
        required: true
        default: dev
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: print input
          run: echo "deploying the application to the ${{inputs.environments}} environment"


